# This is a basic workflow to help you get started with Actions

name: Create_Issues

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  [create, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.6.0
      
      - uses: ddradar/choose-random-action@v2.0.2
        id: pick_diff
        with:
          contents: |
            554
            724
            767
            865

      - uses: ddradar/choose-random-action@v2.0.2
        id: pick_med
        with:
          contents: |
            257
            352
            397
            867

      - uses: ddradar/choose-random-action@v2.0.2
        id: pick_easy
        with:
          contents: |
            354
            485
            687
            889
            932
            979
      
      - name: Create Issue From File (Diff)
        uses: peter-evans/create-issue-from-file@v4.0.1
        with:
          title: Ticket nr. ${{ steps.pick_diff.outputs.selected }}
          content-filepath: ./.issues/diff/issue${{ steps.pick_diff.outputs.selected }}.md
          labels: difficult

      - name: Create Issue From File (Med)
        uses: peter-evans/create-issue-from-file@v4.0.1
        with:
          title: Ticket nr. ${{ steps.pick_med.outputs.selected }}
          content-filepath: ./.issues/med/issue${{ steps.pick_med.outputs.selected }}.md
          labels: medium

      - name: Create Issue From File (Easy)
        uses: peter-evans/create-issue-from-file@v4.0.1
        with:
          title: Ticket nr. ${{ steps.pick_easy.outputs.selected }}
          content-filepath: ./.issues/easy/issue${{ steps.pick_easy.outputs.selected }}.md
          labels: easy
